context:
  version: "3.1.1"

package:
  name: vue-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@vue/language-server/-/language-server-${{ version }}.tgz
  sha256: f1c1f113bf199e6964852856e448b6d1899f00588f1115e4816d6e374390cc41

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "vue-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: High-performance Vue language tooling based-on Volar.js
  homepage: https://github.com/vuejs/language-tools
  repository: https://github.com/vuejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
