context:
  version: "3.3.6"

package:
  name: vue-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@vue/language-server/-/language-server-${{ version }}.tgz
  sha256: 6e00c4d722d04d907e813f4ac596e635829d812a5e9465a1f948c74234a40aa1

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "vue-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: High-performance Vue language tooling based-on Volar.js
  homepage: https://github.com/vuejs/language-tools
  repository: https://github.com/vuejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
