context:
  version: "3.3.4"

package:
  name: vue-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@vue/language-server/-/language-server-${{ version }}.tgz
  sha256: 350779e570705016941aa40be6c246a3b42f7b0f870ce77ea0bdd51224eddc1e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "vue-language-server 2>&1 | grep -q 'Connection input stream is not set.'"

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: High-performance Vue language tooling based-on Volar.js
  homepage: https://github.com/vuejs/language-tools
  repository: https://github.com/vuejs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
